export const SKILL_ALIASES: Record<string, string> = {
  // Languages
  js: 'javascript',
  javascript: 'javascript',
  ts: 'typescript',
  typescript: 'typescript',
  py: 'python',
  python: 'python',
  golang: 'go',
  go: 'go',
  rb: 'ruby',
  ruby: 'ruby',
  rs: 'rust',
  rust: 'rust',
  cpp: 'c++',
  'c++': 'c++',
  cs: 'c#',
  'c#': 'c#',
  kt: 'kotlin',
  kotlin: 'kotlin',
  java: 'java',
  swift: 'swift',
  php: 'php',
  sh: 'bash',
  bash: 'bash',
  shell: 'bash',

  // Frontend
  react: 'react',
  'react.js': 'react',
  reactjs: 'react',
  next: 'next.js',
  'next.js': 'next.js',
  nextjs: 'next.js',
  vue: 'vue.js',
  'vue.js': 'vue.js',
  vuejs: 'vue.js',
  nuxt: 'nuxt.js',
  'nuxt.js': 'nuxt.js',
  svelte: 'svelte',
  sveltekit: 'sveltekit',
  angular: 'angular',
  angularjs: 'angular',
  tailwind: 'tailwindcss',
  tailwindcss: 'tailwindcss',
  css: 'css',
  css3: 'css',
  html: 'html',
  html5: 'html',
  redux: 'redux',
  zustand: 'zustand',
  graphql: 'graphql',
  rest: 'rest api',
  'rest api': 'rest api',
  restful: 'rest api',

  // Backend / Runtimes
  node: 'nodejs',
  'node.js': 'nodejs',
  nodejs: 'nodejs',
  express: 'express.js',
  'express.js': 'express.js',
  fastify: 'fastify',
  nest: 'nestjs',
  nestjs: 'nestjs',
  django: 'django',
  fastapi: 'fastapi',
  flask: 'flask',
  spring: 'spring boot',
  'spring boot': 'spring boot',
  springboot: 'spring boot',
  rails: 'ruby on rails',
  'ruby on rails': 'ruby on rails',

  // Databases & Caches
  postgres: 'postgresql',
  postgresql: 'postgresql',
  psql: 'postgresql',
  mongo: 'mongodb',
  mongodb: 'mongodb',
  mysql: 'mysql',
  redis: 'redis',
  sqlite: 'sqlite',
  cassandra: 'cassandra',
  dynamo: 'dynamodb',
  dynamodb: 'dynamodb',
  elasticsearch: 'elasticsearch',
  elastic: 'elasticsearch',
  neo4j: 'neo4j',
  cockroach: 'cockroachdb',
  cockroachdb: 'cockroachdb',
  snowflake: 'snowflake',
  bigquery: 'bigquery',

  // Cloud & DevOps
  k8s: 'kubernetes',
  kubernetes: 'kubernetes',
  docker: 'docker',
  aws: 'amazon web services',
  'amazon web services': 'amazon web services',
  gcp: 'google cloud platform',
  'google cloud platform': 'google cloud platform',
  azure: 'microsoft azure',
  'microsoft azure': 'microsoft azure',
  terraform: 'terraform',
  tf: 'terraform',
  ansible: 'ansible',
  ci: 'ci/cd',
  cd: 'ci/cd',
  'ci/cd': 'ci/cd',
  'github actions': 'github actions',
  gha: 'github actions',
  circleci: 'circleci',
  jenkins: 'jenkins',
  kafka: 'apache kafka',
  'apache kafka': 'apache kafka',
  rabbitmq: 'rabbitmq',
  grpc: 'grpc',
  protobuf: 'protocol buffers',

  // AI / ML
  ai: 'artificial intelligence',
  ml: 'machine learning',
  pytorch: 'pytorch',
  torch: 'pytorch',
  tensorflow: 'tensorflow',
  tf2: 'tensorflow',
  llm: 'large language models',
  llms: 'large language models',
  langchain: 'langchain',
  llamaindex: 'llamaindex',
  transformers: 'hugging face transformers',
  rag: 'retrieval-augmented generation',
};

export function canonicalizeSkill(skill: string): string {
  const normalized = skill.toLowerCase().trim();
  return SKILL_ALIASES[normalized] || normalized;
}

export function areSkillsEquivalent(skillA: string, skillB: string): boolean {
  return canonicalizeSkill(skillA) === canonicalizeSkill(skillB);
}
